In [162]:
#import pandas
import pandas as pd
#import csv module
import csv

#save file address with needed data as variables
movie_data_to_load = "tmdb_5000_movies.csv"
credits_data_to_load = "tmdb_5000_credits.csv"

# Initialize lists to store the cleaned data
movie_rows = []
credits_rows = []

In [163]:
# Read the movie data file and store the cleaned data in the movie_rows list
with open(movie_data_to_load, 'r', encoding='utf-8') as movie_file:
    csv_reader = csv.reader(movie_file)
    movie_headers = next(csv_reader)
    for row in csv_reader:
        cleaned_row = []
        for item in row:
            cleaned_item = item.replace('\r', '').replace('\n', '\\n')
            cleaned_row.append(cleaned_item)
        movie_rows.append(cleaned_row)

In [164]:
# Read the credits data file and store the cleaned data in the credits_rows list
with open(credits_data_to_load, 'r', encoding='utf-8') as credits_file:
    csv_reader = csv.reader(credits_file)
    credits_headers = next(csv_reader)
    for row in csv_reader:
        cleaned_row = []
        for item in row:
            cleaned_item = item.replace('\r', '').replace('\n', '\\n')
            cleaned_row.append(cleaned_item)
        credits_rows.append(cleaned_row)

In [165]:
# Create Pandas DataFrames from the cleaned data
movie_data = pd.DataFrame(movie_rows, columns=movie_headers)
credits_data = pd.DataFrame(credits_rows, columns=credits_headers)

In [166]:
#count the total number of movies in creadits file by counting the number of rows with movie_id column as reference
movies_count = movie_data['id'].count()

#display count of movies
movies_count

4803

In [167]:
#count the total number of movies in creadits file by counting the number of rows with movie_id column as reference
credits_count = credits_data['movie_id'].count()

#display count of movies
credits_count

4803

In [168]:
# Remove the "genres" and "keywords" columns
movie_data.drop(["genres", "keywords"], axis=1, inplace=True)

movie_data.head()

,budget,homepage,id,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,http://www.avatarmovie.com/,19995,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,http://disney.go.com/disneypictures/pirates/,285,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,http://www.sonypictures.com/movies/spectre/,206647,en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,http://www.thedarkknightrises.com/,49026,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.31295,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,http://movies.disney.com/john-carter,49529,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [169]:
#change column name cast to actors in credits table
credits_data = credits_data.rename(columns={'cast': 'actors'})

#display count of students across all schools
credits_data.head()

,movie_id,title,actors,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [170]:
# Export movie_data to a CSV file
movie_data.to_csv("movie_data.csv", index=False)

# Export credits_data to a CSV file
credits_data.to_csv("credits_data.csv", index=False)